// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Terrible_Programs_Installer
{
    [default_interface]
    runtimeclass ScreenShotData : Microsoft.UI.Xaml.Controls.Control
    {
        ScreenShotData();
        String ImageSource;
    }
}
